const skillData = [
  {
    tool: "C",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg",
    projects: "9",
    level: "Intermediate",
    alt: "C Language Logo",
  },
  {
    tool: "C++",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg",
    projects: "0",
    level: "Beginner",
    alt: "C++ Language Logo",
  },
  {
    tool: "Python",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    projects: "3",
    level: "Intermediate",
    alt: "Python Language Logo",
  },
  {
    tool: "HTML 5",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
    projects: "4",
    level: "Intermediate",
    alt: "HTML Logo",
  },
  {
    tool: "CSS 3",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
    projects: "7",
    level: "Intermediate",
    alt: "CSS Logo",
  },
  {
    tool: "JavaScript",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    projects: "7",
    level: "Intermediate",
    alt: "JavaScript Language Logo",
  },
  {
    tool: "Git",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
    projects: "none",
    level: "Intermediate",
    alt: "Git Logo",
  },
  {
    tool: "GitHub",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
    projects: "none",
    level: "Intermediate",
    alt: "GitHub Logo",
  },
  {
    tool: "Bash",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg",
    projects: "2",
    level: "Beginner",
    alt: "Bash Logo",
  },
  {
    tool: "Docker",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
    projects: "0",
    level: "Beginner",
    alt: "Docker Logo",
  },
  {
    tool: "Nodejs",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    projects: "2",
    level: "Beginner",
    alt: "Node Logo",
  },
  {
    tool: "Express",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
    projects: "2",
    level: "Intermediate",
    alt: "Express Logo",
  },
  {
    tool: "MongoDB",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
    projects: "2",
    level: "Beginner",
    alt: "MongoDB Logo",
  },
  {
    tool: "MySQL",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
    projects: "0",
    level: "Beginner",
    alt: "MySQL Logo",
  },
  {
    tool: "PostgreSQL",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
    projects: "0",
    level: "Beginner",
    alt: "PostgreSQL Logo",
  },
  {
    tool: "Vue",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg",
    projects: "1",
    level: "Intermediate",
    alt: "Vue Logo",
  },
  {
    tool: "React",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    projects: "0",
    level: "Beginner",
    alt: "React Logo",
  },
  {
    tool: "Android Studio",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/androidstudio/androidstudio-original.svg",
    projects: "none",
    level: "Beginner",
    alt: "Android Studio Logo",
  },
  {
    tool: "Java",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
    projects: "1",
    level: "Beginner",
    alt: "Java Logo",
  },
  {
    tool: "Sass",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
    projects: "7",
    level: "Beginner",
    alt: "Sass Logo",
  },
  {
    tool: "VS Code",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg",
    projects: "none",
    level: "Beginner",
    alt: "VS Code Logo",
  },
  {
    tool: "Vim",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vim/vim-original.svg",
    projects: "none",
    level: "Beginner",
    alt: "Vim Logo",
  },
  {
    tool: "Linux",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
    projects: "none",
    level: "Intermediate",
    alt: "Linux Logo",
  },
  {
    tool: "InkScape",
    img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/inkscape/inkscape-original.svg",
    projects: "none",
    level: "Intermediate",
    alt: "Linux Logo",
  },
];

export default skillData;
